module TerminalShop
  module Models
    type address_create_response = { data: String }

    class AddressCreateResponse < TerminalShop::BaseModel
      attr_accessor data: String

      def initialize:
        (data: String) -> void
        | (
          ?TerminalShop::Models::address_create_response
          | TerminalShop::BaseModel data
        ) -> void

      def to_hash: -> TerminalShop::Models::address_create_response
    end
  end
end
