module TerminalShop
  module Models
    type address_delete_response = { data: :ok }

    class AddressDeleteResponse < TerminalShop::BaseModel
      attr_accessor data: :ok

      def initialize:
        (data: :ok) -> void
        | (
          ?TerminalShop::Models::address_delete_response
          | TerminalShop::BaseModel data
        ) -> void

      def to_hash: -> TerminalShop::Models::address_delete_response
    end
  end
end
