module TerminalShop
  module Models
    type app_create_params =
      { name: String, redirect_uri: String } & TerminalShop::request_parameters

    class AppCreateParams < TerminalShop::BaseModel
      extend TerminalShop::RequestParameters::Converter
      include TerminalShop::RequestParameters

      attr_accessor name: String

      attr_accessor redirect_uri: String

      def initialize: (
        name: String,
        redirect_uri: String,
        ?request_options: TerminalShop::request_opts
      ) -> void

      def to_hash: -> TerminalShop::Models::app_create_params
    end
  end
end
