module TerminalShop
  module Models
    type app_delete_params = {  } & TerminalShop::request_parameters

    class AppDeleteParams < TerminalShop::BaseModel
      extend TerminalShop::RequestParameters::Converter
      include TerminalShop::RequestParameters

      def initialize: (?request_options: TerminalShop::request_opts) -> void

      def to_hash: -> TerminalShop::Models::app_delete_params
    end
  end
end
