module TerminalShop
  module Models
    type app_get_params = {  } & TerminalShop::request_parameters

    class AppGetParams < TerminalShop::BaseModel
      extend TerminalShop::RequestParameters::Converter
      include TerminalShop::RequestParameters

      def initialize:
        (request_options: TerminalShop::request_opts) -> void
        | (
          ?TerminalShop::Models::app_get_params | TerminalShop::BaseModel data
        ) -> void

      def to_hash: -> TerminalShop::Models::app_get_params
    end
  end
end
