module TerminalShop
  module Models
    type card_delete_params = {  } & TerminalShop::request_parameters

    class CardDeleteParams < TerminalShop::BaseModel
      extend TerminalShop::RequestParameters::Converter
      include TerminalShop::RequestParameters

      def initialize:
        (?request_options: TerminalShop::request_opts) -> void
        | (
          ?TerminalShop::Models::card_delete_params
          | TerminalShop::BaseModel data
        ) -> void

      def to_hash: -> TerminalShop::Models::card_delete_params
    end
  end
end
