module TerminalShop
  module Models
    type cart_set_card_response = { data: :ok }

    class CartSetCardResponse < TerminalShop::BaseModel
      attr_accessor data: :ok

      def initialize:
        (?data: :ok) -> void
        | (
          ?TerminalShop::Models::cart_set_card_response
          | TerminalShop::BaseModel data
        ) -> void

      def to_hash: -> TerminalShop::Models::cart_set_card_response
    end
  end
end
