module TerminalShop
  module Models
    type cart_convert_params = {  } & TerminalShop::request_parameters

    class CartConvertParams < TerminalShop::BaseModel
      extend TerminalShop::Type::RequestParameters::Converter
      include TerminalShop::RequestParameters

      def initialize: (?request_options: TerminalShop::request_opts) -> void

      def to_hash: -> TerminalShop::Models::cart_convert_params
    end
  end
end
