module TerminalShop
  module Models
    type cart_clear_response = { data: :ok }

    class CartClearResponse < TerminalShop::BaseModel
      attr_accessor data: :ok

      def initialize:
        (data: :ok) -> void
        | (
          ?TerminalShop::Models::cart_clear_response
          | TerminalShop::BaseModel data
        ) -> void

      def to_hash: -> TerminalShop::Models::cart_clear_response
    end
  end
end
