module TerminalShop
  module Models
    type cart_remove_gift_card_params = {  } & TerminalShop::request_parameters

    class CartRemoveGiftCardParams < TerminalShop::BaseModel
      extend TerminalShop::RequestParameters::Converter
      include TerminalShop::RequestParameters

      def initialize:
        (request_options: TerminalShop::request_opts) -> void
        | (
          ?TerminalShop::Models::cart_remove_gift_card_params
          | TerminalShop::BaseModel data
        ) -> void

      def to_hash: -> TerminalShop::Models::cart_remove_gift_card_params
    end
  end
end
