module TerminalShop
  module Models
    type order_list_response = { data: ::Array[TerminalShop::Models::OrderAPI] }

    class OrderListResponse < TerminalShop::BaseModel
      attr_accessor data: ::Array[TerminalShop::Models::OrderAPI]

      def initialize:
        (data: ::Array[TerminalShop::Models::OrderAPI]) -> void
        | (
          ?TerminalShop::Models::order_list_response
          | TerminalShop::BaseModel data
        ) -> void

      def to_hash: -> TerminalShop::Models::order_list_response
    end
  end
end
