module TerminalShop
  module Models
    type order_list_params = {  } & TerminalShop::request_parameters

    class OrderListParams < TerminalShop::BaseModel
      extend TerminalShop::Type::RequestParameters::Converter
      include TerminalShop::RequestParameters

      def initialize: (?request_options: TerminalShop::request_opts) -> void

      def to_hash: -> TerminalShop::Models::order_list_params
    end
  end
end
