module TerminalShop
  module Models
    type product_get_response = { data: TerminalShop::Models::ProductAPI }

    class ProductGetResponse < TerminalShop::BaseModel
      attr_accessor data: TerminalShop::Models::ProductAPI

      def initialize:
        (data: TerminalShop::Models::ProductAPI) -> void
        | (
          ?TerminalShop::Models::product_get_response
          | TerminalShop::BaseModel data
        ) -> void

      def to_hash: -> TerminalShop::Models::product_get_response
    end
  end
end
