module TerminalShop
  module Models
    type product_list_params = {  } & TerminalShop::request_parameters

    class ProductListParams < TerminalShop::BaseModel
      extend TerminalShop::Type::RequestParameters::Converter
      include TerminalShop::RequestParameters

      def initialize: (?request_options: TerminalShop::request_opts) -> void

      def to_hash: -> TerminalShop::Models::product_list_params
    end
  end
end
