module TerminalShop
  module Models
    type profile_update_params =
      { email: String, name: String } & TerminalShop::request_parameters

    class ProfileUpdateParams < TerminalShop::BaseModel
      extend TerminalShop::RequestParameters::Converter
      include TerminalShop::RequestParameters

      attr_accessor email: String

      attr_accessor name: String

      def initialize:
        (
          email: String,
          name: String,
          ?request_options: TerminalShop::request_opts
        ) -> void
        | (
          ?TerminalShop::Models::profile_update_params
          | TerminalShop::BaseModel data
        ) -> void

      def to_hash: -> TerminalShop::Models::profile_update_params
    end
  end
end
