module TerminalShop
  module Models
    type profile_update_response = { data: TerminalShop::Models::ProfileAPI }

    class ProfileUpdateResponse < TerminalShop::BaseModel
      attr_accessor data: TerminalShop::Models::ProfileAPI

      def initialize:
        (data: TerminalShop::Models::ProfileAPI) -> void
        | (
          ?TerminalShop::Models::profile_update_response
          | TerminalShop::BaseModel data
        ) -> void

      def to_hash: -> TerminalShop::Models::profile_update_response
    end
  end
end
