module TerminalShop
  module Models
    type subscription_delete_params = {  } & TerminalShop::request_parameters

    class SubscriptionDeleteParams < TerminalShop::BaseModel
      extend TerminalShop::RequestParameters::Converter
      include TerminalShop::RequestParameters

      def initialize: (?request_options: TerminalShop::request_opts) -> void

      def to_hash: -> TerminalShop::Models::subscription_delete_params
    end
  end
end
