module TerminalShop
  module Models
    type subscription_create_params = {  } & TerminalShop::request_parameters

    class SubscriptionCreateParams < TerminalShop::Models::SubscriptionAPI
      extend TerminalShop::RequestParameters::Converter
      include TerminalShop::RequestParameters

      def initialize: (?request_options: TerminalShop::request_opts) -> void

      def to_hash: -> TerminalShop::Models::subscription_create_params
    end
  end
end
