module TerminalShop
  module Type
    module Converter
      type input = TerminalShop::Type::Converter | Class

      type state =
        {
          strictness: bool | :strong,
          exactness: { yes: Integer, no: Integer, maybe: Integer },
          branched: Integer
        }

      def coerce: (
        top value,
        state: TerminalShop::Type::Converter::state
      ) -> top

      def dump: (top value) -> top

      def self.type_info: (
        {
          const: (nil | bool | Integer | Float | Symbol)?,
          enum: ^-> TerminalShop::Type::Converter::input?,
          union: ^-> TerminalShop::Type::Converter::input?
        }
        | ^-> TerminalShop::Type::Converter::input
        | TerminalShop::Type::Converter::input spec
      ) -> (^-> top)

      def self.coerce: (
        TerminalShop::Type::Converter::input target,
        top value,
        ?state: TerminalShop::Type::Converter::state
      ) -> top

      def self.dump: (
        TerminalShop::Type::Converter::input target,
        top value
      ) -> top
    end
  end
end
