module TerminalShop
  module Type
    class Unknown
      extend TerminalShop::Type::Converter

      def self.===: (top other) -> bool

      def self.==: (top other) -> bool

      def self.coerce: (
        top value,
        state: TerminalShop::Type::Converter::state
      ) -> top

      def self.dump: (top value) -> top
    end
  end
end
