module TerminalShop
  module Models
    type address_create_response = { data: String }

    class AddressCreateResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: String

      def initialize: (data: String) -> void

      def to_hash: -> { data: String }
    end
  end
end
