module TerminalShop
  module Models
    type address_get_response = { data: TerminalShop::AddressAPI }

    class AddressGetResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::AddressAPI

      def initialize: (data: TerminalShop::AddressAPI) -> void

      def to_hash: -> { data: TerminalShop::AddressAPI }
    end
  end
end
