module TerminalShop
  module Models
    type address_delete_params = {  } & TerminalShop::request_parameters

    class AddressDeleteParams < TerminalShop::BaseModel
      extend TerminalShop::Type::RequestParameters::Converter
      include TerminalShop::RequestParameters

      def initialize: (?request_options: TerminalShop::request_opts) -> void

      def to_hash: -> TerminalShop::Models::address_delete_params
    end
  end
end
