module TerminalShop
  module Models
    type address_list_response = { data: ::Array[TerminalShop::AddressAPI] }

    class AddressListResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: ::Array[TerminalShop::AddressAPI]

      def initialize: (data: ::Array[TerminalShop::AddressAPI]) -> void
    end
  end
end
