module TerminalShop
  module Models
    type address_delete_response = { data: :ok }

    class AddressDeleteResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: :ok

      def initialize: (?data: :ok) -> void

      def to_hash: -> { data: :ok }
    end
  end
end
