module TerminalShop
  module Models
    type app_create_response =
      { data: TerminalShop::Models::AppCreateResponse::Data }

    class AppCreateResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::Models::AppCreateResponse::Data

      def initialize: (
        data: TerminalShop::Models::AppCreateResponse::Data
      ) -> void

      type data = { id: String, secret: String }

      class Data < TerminalShop::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor secret: String

        def initialize: (id: String, secret: String) -> void
      end
    end
  end
end
