module TerminalShop
  module Models
    type app_list_response = { data: ::Array[TerminalShop::AppAPI] }

    class AppListResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: ::Array[TerminalShop::AppAPI]

      def initialize: (data: ::Array[TerminalShop::AppAPI]) -> void
    end
  end
end
