module TerminalShop
  module Models
    type app_get_response = { data: TerminalShop::AppAPI }

    class AppGetResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::AppAPI

      def initialize: (data: TerminalShop::AppAPI) -> void
    end
  end
end
