module TerminalShop
  module Models
    type app_list_params =
      {  } & TerminalShop::Internal::Type::request_parameters

    class AppListParams < TerminalShop::Internal::Type::BaseModel
      extend TerminalShop::Internal::Type::RequestParameters::Converter
      include TerminalShop::Internal::Type::RequestParameters

      def initialize: (?request_options: TerminalShop::request_opts) -> void
    end
  end
end
