module TerminalShop
  module Models
    type app_delete_response = { data: :ok }

    class AppDeleteResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: :ok

      def initialize: (?data: :ok) -> void
    end
  end
end
