module TerminalShop
  module Models
    type card_get_params =
      {  } & TerminalShop::Internal::Type::request_parameters

    class CardGetParams < TerminalShop::Internal::Type::BaseModel
      extend TerminalShop::Internal::Type::RequestParameters::Converter
      include TerminalShop::Internal::Type::RequestParameters

      def initialize: (?request_options: TerminalShop::request_opts) -> void

      def to_hash: -> TerminalShop::Models::card_get_params
    end
  end
end
