module TerminalShop
  module Models
    type card_api =
      {
        id: String,
        brand: String,
        created: String,
        expiration: TerminalShop::CardAPI::Expiration,
        :last4 => String
      }

    class CardAPI < TerminalShop::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor brand: String

      attr_accessor created: String

      attr_accessor expiration: TerminalShop::CardAPI::Expiration

      attr_accessor last4: String

      def initialize: (
        id: String,
        brand: String,
        created: String,
        expiration: TerminalShop::CardAPI::Expiration,
        last4: String
      ) -> void

      type expiration = { month: Integer, year: Integer }

      class Expiration < TerminalShop::Internal::Type::BaseModel
        attr_accessor month: Integer

        attr_accessor year: Integer

        def initialize: (month: Integer, year: Integer) -> void
      end
    end
  end
end
