module TerminalShop
  module Models
    type card_create_response = { data: String }

    class CardCreateResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: String

      def initialize: (data: String) -> void
    end
  end
end
