module TerminalShop
  module Models
    type card_get_response = { data: TerminalShop::Models::CardAPI }

    class CardGetResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::Models::CardAPI

      def initialize: (data: TerminalShop::Models::CardAPI) -> void

      def to_hash: -> TerminalShop::Models::card_get_response
    end
  end
end
