module TerminalShop
  module Models
    type card_collect_response =
      { data: TerminalShop::Models::CardCollectResponse::Data }

    class CardCollectResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::Models::CardCollectResponse::Data

      def initialize: (
        data: TerminalShop::Models::CardCollectResponse::Data
      ) -> void

      type data = { url: String }

      class Data < TerminalShop::Internal::Type::BaseModel
        attr_accessor url: String

        def initialize: (url: String) -> void
      end
    end
  end
end
