module TerminalShop
  module Models
    type card_list_response = { data: ::Array[TerminalShop::CardAPI] }

    class CardListResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: ::Array[TerminalShop::CardAPI]

      def initialize: (data: ::Array[TerminalShop::CardAPI]) -> void
    end
  end
end
