module TerminalShop
  module Models
    type cart_set_card_response = { data: :ok }

    class CartSetCardResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: :ok

      def initialize: (?data: :ok) -> void
    end
  end
end
