module TerminalShop
  module Models
    type cart_convert_response = { data: TerminalShop::OrderAPI }

    class CartConvertResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::OrderAPI

      def initialize: (data: TerminalShop::OrderAPI) -> void
    end
  end
end
