module TerminalShop
  module Models
    type cart_clear_response = { data: :ok }

    class CartClearResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: :ok

      def initialize: (?data: :ok) -> void

      def to_hash: -> TerminalShop::Models::cart_clear_response
    end
  end
end
