module TerminalShop
  module Models
    type cart_set_item_params =
      { product_variant_id: String, quantity: Integer }
      & TerminalShop::Internal::Type::request_parameters

    class CartSetItemParams < TerminalShop::Internal::Type::BaseModel
      extend TerminalShop::Internal::Type::RequestParameters::Converter
      include TerminalShop::Internal::Type::RequestParameters

      attr_accessor product_variant_id: String

      attr_accessor quantity: Integer

      def initialize: (
        product_variant_id: String,
        quantity: Integer,
        ?request_options: TerminalShop::request_opts
      ) -> void

      def to_hash: -> {
        product_variant_id: String,
        quantity: Integer,
        request_options: TerminalShop::RequestOptions
      }
    end
  end
end
