module TerminalShop
  module Models
    type cart_get_response = { data: TerminalShop::CartAPI }

    class CartGetResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::CartAPI

      def initialize: (data: TerminalShop::CartAPI) -> void

      def to_hash: -> { data: TerminalShop::CartAPI }
    end
  end
end
