module TerminalShop
  module Models
    type email_create_response = { data: :ok }

    class EmailCreateResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: :ok

      def initialize: (?data: :ok) -> void

      def to_hash: -> TerminalShop::Models::email_create_response
    end
  end
end
