module TerminalShop
  module Models
    type email_create_params =
      { email: String } & TerminalShop::Internal::Type::request_parameters

    class EmailCreateParams < TerminalShop::Internal::Type::BaseModel
      extend TerminalShop::Internal::Type::RequestParameters::Converter
      include TerminalShop::Internal::Type::RequestParameters

      attr_accessor email: String

      def initialize: (
        email: String,
        ?request_options: TerminalShop::request_opts
      ) -> void

      def to_hash: -> {
        email: String,
        request_options: TerminalShop::RequestOptions
      }
    end
  end
end
