module TerminalShop
  module Models
    type order_get_response = { data: TerminalShop::OrderAPI }

    class OrderGetResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::OrderAPI

      def initialize: (data: TerminalShop::OrderAPI) -> void

      def to_hash: -> { data: TerminalShop::OrderAPI }
    end
  end
end
