module TerminalShop
  module Models
    type order_list_response = { data: ::Array[TerminalShop::OrderAPI] }

    class OrderListResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: ::Array[TerminalShop::OrderAPI]

      def initialize: (data: ::Array[TerminalShop::OrderAPI]) -> void

      def to_hash: -> { data: ::Array[TerminalShop::OrderAPI] }
    end
  end
end
