module TerminalShop
  module Models
    type product_get_params =
      { id: String } & TerminalShop::Internal::Type::request_parameters

    class ProductGetParams < TerminalShop::Internal::Type::BaseModel
      extend TerminalShop::Internal::Type::RequestParameters::Converter
      include TerminalShop::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: TerminalShop::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        request_options: TerminalShop::RequestOptions
      }
    end
  end
end
