module TerminalShop
  module Models
    type product_get_response = { data: TerminalShop::ProductAPI }

    class ProductGetResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::ProductAPI

      def initialize: (data: TerminalShop::ProductAPI) -> void

      def to_hash: -> { data: TerminalShop::ProductAPI }
    end
  end
end
