module TerminalShop
  module Models
    type product_api =
      {
        id: String,
        description: String,
        name: String,
        variants: ::Array[TerminalShop::ProductVariant],
        order: Integer,
        subscription: TerminalShop::ProductAPI::subscription,
        tags: TerminalShop::ProductAPI::Tags
      }

    class ProductAPI < TerminalShop::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor description: String

      attr_accessor name: String

      attr_accessor variants: ::Array[TerminalShop::ProductVariant]

      attr_reader order: Integer?

      def order=: (Integer) -> Integer

      attr_reader subscription: TerminalShop::ProductAPI::subscription?

      def subscription=: (
        TerminalShop::ProductAPI::subscription
      ) -> TerminalShop::ProductAPI::subscription

      attr_reader tags: TerminalShop::ProductAPI::Tags?

      def tags=: (
        TerminalShop::ProductAPI::Tags
      ) -> TerminalShop::ProductAPI::Tags

      def initialize: (
        id: String,
        description: String,
        name: String,
        variants: ::Array[TerminalShop::ProductVariant],
        ?order: Integer,
        ?subscription: TerminalShop::ProductAPI::subscription,
        ?tags: TerminalShop::ProductAPI::Tags
      ) -> void

      type subscription = :allowed | :required

      module Subscription
        extend TerminalShop::Internal::Type::Enum

        ALLOWED: :allowed
        REQUIRED: :required

        def self?.values: -> ::Array[TerminalShop::ProductAPI::subscription]
      end

      type tags =
        {
          app: String,
          color: String,
          featured: bool,
          market_eu: bool,
          market_global: bool,
          market_na: bool
        }

      class Tags < TerminalShop::Internal::Type::BaseModel
        attr_reader app: String?

        def app=: (String) -> String

        attr_reader color: String?

        def color=: (String) -> String

        attr_reader featured: bool?

        def featured=: (bool) -> bool

        attr_reader market_eu: bool?

        def market_eu=: (bool) -> bool

        attr_reader market_global: bool?

        def market_global=: (bool) -> bool

        attr_reader market_na: bool?

        def market_na=: (bool) -> bool

        def initialize: (
          ?app: String,
          ?color: String,
          ?featured: bool,
          ?market_eu: bool,
          ?market_global: bool,
          ?market_na: bool
        ) -> void
      end
    end
  end
end
