module TerminalShop
  module Models
    type product_list_response = { data: ::Array[TerminalShop::ProductAPI] }

    class ProductListResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: ::Array[TerminalShop::ProductAPI]

      def initialize: (data: ::Array[TerminalShop::ProductAPI]) -> void

      def to_hash: -> { data: ::Array[TerminalShop::ProductAPI] }
    end
  end
end
