module TerminalShop
  module Models
    type profile_update_response = { data: TerminalShop::ProfileAPI }

    class ProfileUpdateResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::ProfileAPI

      def initialize: (data: TerminalShop::ProfileAPI) -> void

      def to_hash: -> { data: TerminalShop::ProfileAPI }
    end
  end
end
