module TerminalShop
  module Models
    type profile_api = { user: TerminalShop::ProfileAPI::User }

    class ProfileAPI < TerminalShop::Internal::Type::BaseModel
      attr_accessor user: TerminalShop::ProfileAPI::User

      def initialize: (user: TerminalShop::ProfileAPI::User) -> void

      type user =
        {
          id: String,
          email: String?,
          fingerprint: String?,
          name: String?,
          stripe_customer_id: String
        }

      class User < TerminalShop::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor email: String?

        attr_accessor fingerprint: String?

        attr_accessor name: String?

        attr_accessor stripe_customer_id: String

        def initialize: (
          id: String,
          email: String?,
          fingerprint: String?,
          name: String?,
          stripe_customer_id: String
        ) -> void
      end
    end
  end
end
