module TerminalShop
  module Models
    type profile_me_response = { data: TerminalShop::ProfileAPI }

    class ProfileMeResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::ProfileAPI

      def initialize: (data: TerminalShop::ProfileAPI) -> void
    end
  end
end
