module TerminalShop
  module Models
    type subscription_api =
      {
        id: String,
        address_id: String,
        card_id: String,
        created: String,
        price: Integer,
        product_variant_id: String,
        quantity: Integer,
        next_: String,
        schedule: TerminalShop::SubscriptionAPI::schedule
      }

    class SubscriptionAPI < TerminalShop::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor address_id: String

      attr_accessor card_id: String

      attr_accessor created: String

      attr_accessor price: Integer

      attr_accessor product_variant_id: String

      attr_accessor quantity: Integer

      attr_reader next_: String?

      def next_=: (String) -> String

      attr_reader schedule: TerminalShop::SubscriptionAPI::schedule?

      def schedule=: (
        TerminalShop::SubscriptionAPI::schedule
      ) -> TerminalShop::SubscriptionAPI::schedule

      def initialize: (
        id: String,
        address_id: String,
        card_id: String,
        created: String,
        price: Integer,
        product_variant_id: String,
        quantity: Integer,
        ?next_: String,
        ?schedule: TerminalShop::SubscriptionAPI::schedule
      ) -> void

      type schedule =
        TerminalShop::SubscriptionAPI::Schedule::Fixed
        | TerminalShop::SubscriptionAPI::Schedule::Weekly

      module Schedule
        extend TerminalShop::Internal::Type::Union

        type fixed = { type: :fixed }

        class Fixed < TerminalShop::Internal::Type::BaseModel
          attr_accessor type: :fixed

          def initialize: (?type: :fixed) -> void
        end

        type weekly = { interval: Integer, type: :weekly }

        class Weekly < TerminalShop::Internal::Type::BaseModel
          attr_accessor interval: Integer

          attr_accessor type: :weekly

          def initialize: (interval: Integer, ?type: :weekly) -> void
        end

        def self?.variants: -> ::Array[TerminalShop::SubscriptionAPI::schedule]
      end
    end
  end
end
