module TerminalShop
  module Models
    type subscription_update_response = { data: TerminalShop::SubscriptionAPI }

    class SubscriptionUpdateResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::SubscriptionAPI

      def initialize: (data: TerminalShop::SubscriptionAPI) -> void
    end
  end
end
