module TerminalShop
  module Models
    type subscription_list_params =
      {  } & TerminalShop::Internal::Type::request_parameters

    class SubscriptionListParams < TerminalShop::BaseModel
      extend TerminalShop::Internal::Type::RequestParameters::Converter
      include TerminalShop::Internal::Type::RequestParameters

      def initialize: (?request_options: TerminalShop::request_opts) -> void

      def to_hash: -> TerminalShop::Models::subscription_list_params
    end
  end
end
