module TerminalShop
  module Models
    type subscription_list_response =
      { data: ::Array[TerminalShop::SubscriptionAPI] }

    class SubscriptionListResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: ::Array[TerminalShop::SubscriptionAPI]

      def initialize: (data: ::Array[TerminalShop::SubscriptionAPI]) -> void
    end
  end
end
