module TerminalShop
  module Models
    type subscription_get_response = { data: TerminalShop::SubscriptionAPI }

    class SubscriptionGetResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::SubscriptionAPI

      def initialize: (data: TerminalShop::SubscriptionAPI) -> void

      def to_hash: -> { data: TerminalShop::SubscriptionAPI }
    end
  end
end
