module TerminalShop
  module Models
    type token_list_response = { data: ::Array[TerminalShop::TokenAPI] }

    class TokenListResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: ::Array[TerminalShop::TokenAPI]

      def initialize: (data: ::Array[TerminalShop::TokenAPI]) -> void
    end
  end
end
