module TerminalShop
  module Models
    type token_get_response = { data: TerminalShop::Models::TokenAPI }

    class TokenGetResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::Models::TokenAPI

      def initialize: (data: TerminalShop::Models::TokenAPI) -> void

      def to_hash: -> TerminalShop::Models::token_get_response
    end
  end
end
