module TerminalShop
  module Models
    type token_get_response = { data: TerminalShop::TokenAPI }

    class TokenGetResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::TokenAPI

      def initialize: (data: TerminalShop::TokenAPI) -> void

      def to_hash: -> { data: TerminalShop::TokenAPI }
    end
  end
end
