module TerminalShop
  module Models
    type token_create_response =
      { data: TerminalShop::Models::TokenCreateResponse::Data }

    class TokenCreateResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::Models::TokenCreateResponse::Data

      def initialize: (
        data: TerminalShop::Models::TokenCreateResponse::Data
      ) -> void

      type data = { id: String, token: String }

      class Data < TerminalShop::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor token: String

        def initialize: (id: String, token: String) -> void
      end
    end
  end
end
