module TerminalShop
  module Models
    type token_api = { id: String, token: String, created: String }

    class TokenAPI < TerminalShop::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor token: String

      attr_accessor created: String

      def initialize: (id: String, token: String, created: String) -> void

      def to_hash: -> { id: String, token: String, created: String }
    end
  end
end
