module TerminalShop
  module Models
    type token_get_params =
      {  } & TerminalShop::Internal::Type::request_parameters

    class TokenGetParams < TerminalShop::Internal::Type::BaseModel
      extend TerminalShop::Internal::Type::RequestParameters::Converter
      include TerminalShop::Internal::Type::RequestParameters

      def initialize: (?request_options: TerminalShop::request_opts) -> void

      def to_hash: -> { request_options: TerminalShop::RequestOptions }
    end
  end
end
