module TerminalShop
  module Models
    type view_init_response =
      { data: TerminalShop::Models::ViewInitResponse::Data }

    class ViewInitResponse < TerminalShop::Internal::Type::BaseModel
      attr_accessor data: TerminalShop::Models::ViewInitResponse::Data

      def initialize: (
        data: TerminalShop::Models::ViewInitResponse::Data
      ) -> void

      def to_hash: -> { data: TerminalShop::Models::ViewInitResponse::Data }

      type data =
        {
          addresses: ::Array[TerminalShop::AddressAPI],
          apps: ::Array[TerminalShop::AppAPI],
          cards: ::Array[TerminalShop::CardAPI],
          cart: TerminalShop::CartAPI,
          orders: ::Array[TerminalShop::OrderAPI],
          products: ::Array[TerminalShop::ProductAPI],
          profile: TerminalShop::ProfileAPI,
          region: TerminalShop::Models::region,
          subscriptions: ::Array[TerminalShop::SubscriptionAPI],
          tokens: ::Array[TerminalShop::TokenAPI]
        }

      class Data < TerminalShop::Internal::Type::BaseModel
        attr_accessor addresses: ::Array[TerminalShop::AddressAPI]

        attr_accessor apps: ::Array[TerminalShop::AppAPI]

        attr_accessor cards: ::Array[TerminalShop::CardAPI]

        attr_accessor cart: TerminalShop::CartAPI

        attr_accessor orders: ::Array[TerminalShop::OrderAPI]

        attr_accessor products: ::Array[TerminalShop::ProductAPI]

        attr_accessor profile: TerminalShop::ProfileAPI

        attr_accessor region: TerminalShop::Models::region

        attr_accessor subscriptions: ::Array[TerminalShop::SubscriptionAPI]

        attr_accessor tokens: ::Array[TerminalShop::TokenAPI]

        def initialize: (
          addresses: ::Array[TerminalShop::AddressAPI],
          apps: ::Array[TerminalShop::AppAPI],
          cards: ::Array[TerminalShop::CardAPI],
          cart: TerminalShop::CartAPI,
          orders: ::Array[TerminalShop::OrderAPI],
          products: ::Array[TerminalShop::ProductAPI],
          profile: TerminalShop::ProfileAPI,
          region: TerminalShop::Models::region,
          subscriptions: ::Array[TerminalShop::SubscriptionAPI],
          tokens: ::Array[TerminalShop::TokenAPI]
        ) -> void

        def to_hash: -> {
          addresses: ::Array[TerminalShop::AddressAPI],
          apps: ::Array[TerminalShop::AppAPI],
          cards: ::Array[TerminalShop::CardAPI],
          cart: TerminalShop::CartAPI,
          orders: ::Array[TerminalShop::OrderAPI],
          products: ::Array[TerminalShop::ProductAPI],
          profile: TerminalShop::ProfileAPI,
          region: TerminalShop::Models::region,
          subscriptions: ::Array[TerminalShop::SubscriptionAPI],
          tokens: ::Array[TerminalShop::TokenAPI]
        }
      end
    end
  end
end
