module TerminalShop
  class Unknown = TerminalShop::Internal::Type::Unknown

  class BooleanModel = TerminalShop::Internal::Type::BooleanModel

  module Enum = TerminalShop::Internal::Type::Enum

  module Union = TerminalShop::Internal::Type::Union

  class ArrayOf = TerminalShop::Internal::Type::ArrayOf

  class HashOf = TerminalShop::Internal::Type::HashOf

  class BaseModel = TerminalShop::Internal::Type::BaseModel

  type request_parameters = TerminalShop::Internal::Type::request_parameters

  module RequestParameters = TerminalShop::Internal::Type::RequestParameters
end
