module TerminalShop
  module Errors
    class Error < StandardError
      attr_accessor cause: StandardError?
    end

    class ConversionError < TerminalShop::Errors::Error
    end

    class APIError < TerminalShop::Errors::Error
      attr_accessor url: URI::Generic

      attr_accessor status: Integer?

      attr_accessor body: top?

      def initialize: (
        url: URI::Generic,
        ?status: Integer?,
        ?body: Object?,
        ?request: nil,
        ?response: nil,
        ?message: String?
      ) -> void
    end

    class APIConnectionError < TerminalShop::Errors::APIError
      def initialize: (
        url: URI::Generic,
        ?status: nil,
        ?body: nil,
        ?request: nil,
        ?response: nil,
        ?message: String?
      ) -> void
    end

    class APITimeoutError < TerminalShop::Errors::APIConnectionError
      def initialize: (
        url: URI::Generic,
        ?status: nil,
        ?body: nil,
        ?request: nil,
        ?response: nil,
        ?message: String?
      ) -> void
    end

    class APIStatusError < TerminalShop::Errors::APIError
      def self.for: (
        url: URI::Generic,
        status: Integer,
        body: Object?,
        request: nil,
        response: nil,
        ?message: String?
      ) -> instance

      def initialize: (
        url: URI::Generic,
        status: Integer,
        body: Object?,
        request: nil,
        response: nil,
        ?message: String?
      ) -> void
    end

    class BadRequestError < TerminalShop::Errors::APIStatusError
      HTTP_STATUS: 400
    end

    class AuthenticationError < TerminalShop::Errors::APIStatusError
      HTTP_STATUS: 401
    end

    class PermissionDeniedError < TerminalShop::Errors::APIStatusError
      HTTP_STATUS: 403
    end

    class NotFoundError < TerminalShop::Errors::APIStatusError
      HTTP_STATUS: 404
    end

    class ConflictError < TerminalShop::Errors::APIStatusError
      HTTP_STATUS: 409
    end

    class UnprocessableEntityError < TerminalShop::Errors::APIStatusError
      HTTP_STATUS: 422
    end

    class RateLimitError < TerminalShop::Errors::APIStatusError
      HTTP_STATUS: 429
    end

    class InternalServerError < TerminalShop::Errors::APIStatusError
      HTTP_STATUS: Range[Integer]
    end
  end

  class Error = TerminalShop::Errors::Error

  class ConversionError = TerminalShop::Errors::ConversionError

  class APIError = TerminalShop::Errors::APIError

  class APIStatusError = TerminalShop::Errors::APIStatusError

  class APIConnectionError = TerminalShop::Errors::APIConnectionError

  class APITimeoutError = TerminalShop::Errors::APITimeoutError

  class BadRequestError = TerminalShop::Errors::BadRequestError

  class AuthenticationError = TerminalShop::Errors::AuthenticationError

  class PermissionDeniedError = TerminalShop::Errors::PermissionDeniedError

  class NotFoundError = TerminalShop::Errors::NotFoundError

  class ConflictError = TerminalShop::Errors::ConflictError

  class UnprocessableEntityError = TerminalShop::Errors::UnprocessableEntityError

  class RateLimitError = TerminalShop::Errors::RateLimitError

  class InternalServerError = TerminalShop::Errors::InternalServerError
end
