module TerminalShop
  class Unknown = TerminalShop::Type::Unknown

  class BooleanModel = TerminalShop::Type::BooleanModel

  module Enum = TerminalShop::Type::Enum

  module Union = TerminalShop::Type::Union

  class ArrayOf = TerminalShop::Type::ArrayOf

  class HashOf = TerminalShop::Type::HashOf

  class BaseModel = TerminalShop::Type::BaseModel

  type request_parameters = TerminalShop::Type::request_parameters

  module RequestParameters = TerminalShop::Type::RequestParameters

  module Type
  end
end
