module TerminalShop
  module Resources
    class Order
      def list:
        (
          ?TerminalShop::Models::OrderListParams | Hash[Symbol, top] params
        ) -> TerminalShop::Models::OrderListResponse
        | (
          request_options: TerminalShop::request_opts
        ) -> TerminalShop::Models::OrderListResponse

      def get:
        (
          String id,
          ?TerminalShop::Models::OrderGetParams | Hash[Symbol, top] params
        ) -> TerminalShop::Models::OrderGetResponse
        | (
          String id,
          request_options: TerminalShop::request_opts
        ) -> TerminalShop::Models::OrderGetResponse

      def initialize: (client: TerminalShop::Client) -> void
    end
  end
end
