module TerminalShop
  module Resources
    class Profile
      def update: (
        email: String,
        name: String,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::ProfileUpdateResponse

      def me: (
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::ProfileMeResponse

      def initialize: (client: TerminalShop::Client) -> void
    end
  end
end
