module TerminalShop
  module Resources
    class Subscription
      def create:
        (
          TerminalShop::Models::SubscriptionCreateParams
          | ::Hash[Symbol, top] params
        ) -> TerminalShop::Models::SubscriptionCreateResponse
        | (
          id: String,
          address_id: String,
          card_id: String,
          product_variant_id: String,
          quantity: Integer,
          ?next_: String,
          ?schedule: TerminalShop::Models::SubscriptionAPI::schedule,
          ?request_options: TerminalShop::request_opts
        ) -> TerminalShop::Models::SubscriptionCreateResponse

      def list:
        (
          ?TerminalShop::Models::SubscriptionListParams
          | ::Hash[Symbol, top] params
        ) -> TerminalShop::Models::SubscriptionListResponse
        | (
          ?request_options: TerminalShop::request_opts
        ) -> TerminalShop::Models::SubscriptionListResponse

      def delete:
        (
          String id,
          ?TerminalShop::Models::SubscriptionDeleteParams
          | ::Hash[Symbol, top] params
        ) -> TerminalShop::Models::SubscriptionDeleteResponse
        | (
          String id,
          ?request_options: TerminalShop::request_opts
        ) -> TerminalShop::Models::SubscriptionDeleteResponse

      def get:
        (
          String id,
          ?TerminalShop::Models::SubscriptionGetParams
          | ::Hash[Symbol, top] params
        ) -> TerminalShop::Models::SubscriptionGetResponse
        | (
          String id,
          ?request_options: TerminalShop::request_opts
        ) -> TerminalShop::Models::SubscriptionGetResponse

      def initialize: (client: TerminalShop::Client) -> void
    end
  end
end
