module TerminalShop
  module Resources
    class Token
      def create: (
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::TokenCreateResponse

      def list: (
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::TokenListResponse

      def delete: (
        String id,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::TokenDeleteResponse

      def get: (
        String id,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::TokenGetResponse

      def initialize: (client: TerminalShop::Client) -> void
    end
  end
end
