module TerminalShop
  module Resources
    class View
      def init: (
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::ViewInitResponse

      def initialize: (client: TerminalShop::Client) -> void
    end
  end
end
