# frozen_string_literal: true

# Standard libraries.
require "English"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) && caller.chain([$PROGRAM_NAME]).chain(ARGV).grep(/tapioca/)
  Warning.warn(
    <<~WARN
      \n
      ⚠️ skipped loading of "terminal_shop" gem under `tapioca`.

      This message is normal and expected if you are running a `tapioca` command, and does not impact `.rbi` generation.
      \n
    WARN
  )
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "terminal_shop/version"
require_relative "terminal_shop/internal/util"
require_relative "terminal_shop/internal/type/converter"
require_relative "terminal_shop/internal/type/unknown"
require_relative "terminal_shop/internal/type/boolean_model"
require_relative "terminal_shop/internal/type/enum"
require_relative "terminal_shop/internal/type/union"
require_relative "terminal_shop/internal/type/array_of"
require_relative "terminal_shop/internal/type/hash_of"
require_relative "terminal_shop/internal/type/base_model"
require_relative "terminal_shop/internal/type/base_page"
require_relative "terminal_shop/internal/type/request_parameters"
require_relative "terminal_shop/internal"
require_relative "terminal_shop/request_options"
require_relative "terminal_shop/errors"
require_relative "terminal_shop/internal/transport/base_client"
require_relative "terminal_shop/internal/transport/pooled_net_requester"
require_relative "terminal_shop/client"
require_relative "terminal_shop/models/subscription"
require_relative "terminal_shop/models/address"
require_relative "terminal_shop/models/address_create_params"
require_relative "terminal_shop/models/address_create_response"
require_relative "terminal_shop/models/address_delete_params"
require_relative "terminal_shop/models/address_delete_response"
require_relative "terminal_shop/models/address_get_params"
require_relative "terminal_shop/models/address_get_response"
require_relative "terminal_shop/models/address_list_params"
require_relative "terminal_shop/models/address_list_response"
require_relative "terminal_shop/models/app"
require_relative "terminal_shop/models/app_create_params"
require_relative "terminal_shop/models/app_create_response"
require_relative "terminal_shop/models/app_delete_params"
require_relative "terminal_shop/models/app_delete_response"
require_relative "terminal_shop/models/app_get_params"
require_relative "terminal_shop/models/app_get_response"
require_relative "terminal_shop/models/app_list_params"
require_relative "terminal_shop/models/app_list_response"
require_relative "terminal_shop/models/card"
require_relative "terminal_shop/models/card_collect_params"
require_relative "terminal_shop/models/card_collect_response"
require_relative "terminal_shop/models/card_create_params"
require_relative "terminal_shop/models/card_create_response"
require_relative "terminal_shop/models/card_delete_params"
require_relative "terminal_shop/models/card_delete_response"
require_relative "terminal_shop/models/card_get_params"
require_relative "terminal_shop/models/card_get_response"
require_relative "terminal_shop/models/card_list_params"
require_relative "terminal_shop/models/card_list_response"
require_relative "terminal_shop/models/cart"
require_relative "terminal_shop/models/cart_clear_params"
require_relative "terminal_shop/models/cart_clear_response"
require_relative "terminal_shop/models/cart_convert_params"
require_relative "terminal_shop/models/cart_convert_response"
require_relative "terminal_shop/models/cart_get_params"
require_relative "terminal_shop/models/cart_get_response"
require_relative "terminal_shop/models/cart_set_address_params"
require_relative "terminal_shop/models/cart_set_address_response"
require_relative "terminal_shop/models/cart_set_card_params"
require_relative "terminal_shop/models/cart_set_card_response"
require_relative "terminal_shop/models/cart_set_item_params"
require_relative "terminal_shop/models/cart_set_item_response"
require_relative "terminal_shop/models/email_create_params"
require_relative "terminal_shop/models/email_create_response"
require_relative "terminal_shop/models/order"
require_relative "terminal_shop/models/order_create_params"
require_relative "terminal_shop/models/order_create_response"
require_relative "terminal_shop/models/order_get_params"
require_relative "terminal_shop/models/order_get_response"
require_relative "terminal_shop/models/order_list_params"
require_relative "terminal_shop/models/order_list_response"
require_relative "terminal_shop/models/product"
require_relative "terminal_shop/models/product_get_params"
require_relative "terminal_shop/models/product_get_response"
require_relative "terminal_shop/models/product_list_params"
require_relative "terminal_shop/models/product_list_response"
require_relative "terminal_shop/models/product_variant"
require_relative "terminal_shop/models/profile"
require_relative "terminal_shop/models/profile_me_params"
require_relative "terminal_shop/models/profile_me_response"
require_relative "terminal_shop/models/profile_update_params"
require_relative "terminal_shop/models/profile_update_response"
require_relative "terminal_shop/models/region"
require_relative "terminal_shop/models/subscription_create_params"
require_relative "terminal_shop/models/subscription_create_response"
require_relative "terminal_shop/models/subscription_delete_params"
require_relative "terminal_shop/models/subscription_delete_response"
require_relative "terminal_shop/models/subscription_get_params"
require_relative "terminal_shop/models/subscription_get_response"
require_relative "terminal_shop/models/subscription_list_params"
require_relative "terminal_shop/models/subscription_list_response"
require_relative "terminal_shop/models/token"
require_relative "terminal_shop/models/token_create_params"
require_relative "terminal_shop/models/token_create_response"
require_relative "terminal_shop/models/token_delete_params"
require_relative "terminal_shop/models/token_delete_response"
require_relative "terminal_shop/models/token_get_params"
require_relative "terminal_shop/models/token_get_response"
require_relative "terminal_shop/models/token_list_params"
require_relative "terminal_shop/models/token_list_response"
require_relative "terminal_shop/models/view_init_params"
require_relative "terminal_shop/models/view_init_response"
require_relative "terminal_shop/resources/address"
require_relative "terminal_shop/resources/app"
require_relative "terminal_shop/resources/card"
require_relative "terminal_shop/resources/cart"
require_relative "terminal_shop/resources/email"
require_relative "terminal_shop/resources/order"
require_relative "terminal_shop/resources/product"
require_relative "terminal_shop/resources/profile"
require_relative "terminal_shop/resources/subscription"
require_relative "terminal_shop/resources/token"
require_relative "terminal_shop/resources/view"
