module Terminal
  module Resources
    class Card
      def create:
        (
          Terminal::Models::CardCreateParams | Hash[Symbol, top] params
        ) -> Terminal::Models::CardCreateResponse
        | (
          token: String,
          request_options: Terminal::request_opts
        ) -> Terminal::Models::CardCreateResponse

      def list:
        (
          ?Terminal::Models::CardListParams | Hash[Symbol, top] params
        ) -> Terminal::Models::CardListResponse
        | (
          request_options: Terminal::request_opts
        ) -> Terminal::Models::CardListResponse

      def delete:
        (
          String id,
          ?Terminal::Models::CardDeleteParams | Hash[Symbol, top] params
        ) -> Terminal::Models::CardDeleteResponse
        | (
          String id,
          request_options: Terminal::request_opts
        ) -> Terminal::Models::CardDeleteResponse

      def collect:
        (
          ?Terminal::Models::CardCollectParams | Hash[Symbol, top] params
        ) -> Terminal::Models::CardCollectResponse
        | (
          request_options: Terminal::request_opts
        ) -> Terminal::Models::CardCollectResponse

      def initialize: (client: Terminal::Client) -> void
    end
  end
end
