module Terminal
  module Resources
    class Cart
      def convert:
        (
          ?Terminal::Models::CartConvertParams | Hash[Symbol, top] params
        ) -> Terminal::Models::CartConvertResponse
        | (
          request_options: Terminal::request_opts
        ) -> Terminal::Models::CartConvertResponse

      def get:
        (
          ?Terminal::Models::CartGetParams | Hash[Symbol, top] params
        ) -> Terminal::Models::CartGetResponse
        | (
          request_options: Terminal::request_opts
        ) -> Terminal::Models::CartGetResponse

      def set_address:
        (
          Terminal::Models::CartSetAddressParams | Hash[Symbol, top] params
        ) -> Terminal::Models::CartSetAddressResponse
        | (
          address_id: String,
          request_options: Terminal::request_opts
        ) -> Terminal::Models::CartSetAddressResponse

      def set_card:
        (
          Terminal::Models::CartSetCardParams | Hash[Symbol, top] params
        ) -> Terminal::Models::CartSetCardResponse
        | (
          card_id: String,
          request_options: Terminal::request_opts
        ) -> Terminal::Models::CartSetCardResponse

      def set_item:
        (
          Terminal::Models::CartSetItemParams | Hash[Symbol, top] params
        ) -> Terminal::Models::CartSetItemResponse
        | (
          product_variant_id: String,
          quantity: Integer,
          request_options: Terminal::request_opts
        ) -> Terminal::Models::CartSetItemResponse

      def initialize: (client: Terminal::Client) -> void
    end
  end
end
