module Terminal
  module Resources
    class Subscription
      def create:
        (
          Terminal::Models::SubscriptionCreateParams | Hash[Symbol, top] params
        ) -> Terminal::Models::SubscriptionCreateResponse
        | (
          id: String,
          address_id: String,
          card_id: String,
          frequency: Terminal::Models::SubscriptionAPI::frequency,
          product_variant_id: String,
          quantity: Integer,
          next_: String,
          request_options: Terminal::request_opts
        ) -> Terminal::Models::SubscriptionCreateResponse

      def list:
        (
          ?Terminal::Models::SubscriptionListParams | Hash[Symbol, top] params
        ) -> Terminal::Models::SubscriptionListResponse
        | (
          request_options: Terminal::request_opts
        ) -> Terminal::Models::SubscriptionListResponse

      def delete:
        (
          String id,
          ?Terminal::Models::SubscriptionDeleteParams | Hash[Symbol, top] params
        ) -> Terminal::Models::SubscriptionDeleteResponse
        | (
          String id,
          request_options: Terminal::request_opts
        ) -> Terminal::Models::SubscriptionDeleteResponse

      def initialize: (client: Terminal::Client) -> void
    end
  end
end
