module Terminal
  module Resources
    class View
      def init:
        (
          ?Terminal::Models::ViewInitParams | Hash[Symbol, top] params
        ) -> Terminal::Models::ViewInitResponse
        | (
          request_options: Terminal::request_opts
        ) -> Terminal::Models::ViewInitResponse

      def initialize: (client: Terminal::Client) -> void
    end
  end
end
