module TerminalShop
  module Resources
    class Address
      def create: (
        city: String,
        country: String,
        name: String,
        street1: String,
        zip: String,
        ?phone: String,
        ?province: String,
        ?street2: String,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::AddressCreateResponse

      def list: (
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::AddressListResponse

      def delete: (
        String id,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::AddressDeleteResponse

      def get: (
        String id,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::AddressGetResponse

      def initialize: (client: TerminalShop::Client) -> void
    end
  end
end
