module TerminalShop
  module Resources
    class Card
      def create: (
        token: String,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::CardCreateResponse

      def list: (
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::CardListResponse

      def delete: (
        String id,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::CardDeleteResponse

      def collect: (
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::CardCollectResponse

      def get: (
        String id,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::CardGetResponse

      def initialize: (client: TerminalShop::Client) -> void
    end
  end
end
