module TerminalShop
  module Resources
    class Cart
      def clear: (
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::CartClearResponse

      def convert: (
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::CartConvertResponse

      def get: (
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::CartGetResponse

      def set_address: (
        address_id: String,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::CartSetAddressResponse

      def set_card: (
        card_id: String,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::CartSetCardResponse

      def set_item: (
        product_variant_id: String,
        quantity: Integer,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::CartSetItemResponse

      def initialize: (client: TerminalShop::Client) -> void
    end
  end
end
