module TerminalShop
  module Resources
    class Order
      def create: (
        address_id: String,
        card_id: String,
        variants: ::Hash[Symbol, Integer],
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::OrderCreateResponse

      def list: (
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::OrderListResponse

      def get: (
        String id,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::OrderGetResponse

      def initialize: (client: TerminalShop::Client) -> void
    end
  end
end
