module TerminalShop
  module Resources
    class Product
      def list: (
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::ProductListResponse

      def get: (
        String id,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::ProductGetResponse

      def initialize: (client: TerminalShop::Client) -> void
    end
  end
end
