module TerminalShop
  module Resources
    class Subscription
      def create: (
        id: String,
        address_id: String,
        card_id: String,
        created: String,
        price: Integer,
        product_variant_id: String,
        quantity: Integer,
        ?next_: String,
        ?schedule: TerminalShop::Models::SubscriptionAPI::schedule,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::SubscriptionCreateResponse

      def update: (
        String id,
        ?address_id: String,
        ?card_id: String,
        ?schedule: TerminalShop::Models::SubscriptionUpdateParams::schedule,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::SubscriptionUpdateResponse

      def list: (
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::SubscriptionListResponse

      def delete: (
        String id,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::SubscriptionDeleteResponse

      def get: (
        String id,
        ?request_options: TerminalShop::request_opts
      ) -> TerminalShop::Models::SubscriptionGetResponse

      def initialize: (client: TerminalShop::Client) -> void
    end
  end
end
