module Terminal
  module Models
    type address_list_response = { data: Array[Terminal::Models::AddressAPI] }

    class AddressListResponse < Terminal::BaseModel
      attr_accessor data: Array[Terminal::Models::AddressAPI]

      def initialize:
        (data: Array[Terminal::Models::AddressAPI]) -> void
        | (
          ?Terminal::Models::address_list_response | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::address_list_response
    end
  end
end
