module Terminal
  module Models
    type app_get_response = { data: Terminal::Models::AppAPI }

    class AppGetResponse < Terminal::BaseModel
      attr_accessor data: Terminal::Models::AppAPI

      def initialize:
        (data: Terminal::Models::AppAPI) -> void
        | (
          ?Terminal::Models::app_get_response | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::app_get_response
    end
  end
end
