module Terminal
  module Models
    type app_list_params = {  } & Terminal::request_parameters

    class AppListParams < Terminal::BaseModel
      extend Terminal::RequestParameters::Converter
      include Terminal::RequestParameters

      def initialize:
        (request_options: Terminal::request_opts) -> void
        | (
          ?Terminal::Models::app_list_params | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::app_list_params
    end
  end
end
