module Terminal
  module Models
    type card_collect_response =
      { data: Terminal::Models::CardCollectResponse::Data }

    class CardCollectResponse < Terminal::BaseModel
      attr_accessor data: Terminal::Models::CardCollectResponse::Data

      def initialize:
        (data: Terminal::Models::CardCollectResponse::Data) -> void
        | (
          ?Terminal::Models::card_collect_response | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::card_collect_response

      type data = { url: String }

      class Data < Terminal::BaseModel
        attr_accessor url: String

        def initialize:
          (url: String) -> void
          | (
            ?Terminal::Models::CardCollectResponse::data
            | Terminal::BaseModel data
          ) -> void

        def to_hash: -> Terminal::Models::CardCollectResponse::data
      end
    end
  end
end
