module Terminal
  module Models
    type card_delete_params = {  } & Terminal::request_parameters

    class CardDeleteParams < Terminal::BaseModel
      extend Terminal::RequestParameters::Converter
      include Terminal::RequestParameters

      def initialize:
        (request_options: Terminal::request_opts) -> void
        | (
          ?Terminal::Models::card_delete_params | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::card_delete_params
    end
  end
end
