module Terminal
  module Models
    type cart_set_card_response = { data: :ok }

    class CartSetCardResponse < Terminal::BaseModel
      attr_accessor data: :ok

      def initialize:
        (data: :ok) -> void
        | (
          ?Terminal::Models::cart_set_card_response | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::cart_set_card_response
    end
  end
end
