module Terminal
  module Models
    type cart_set_card_params =
      { card_id: String } & Terminal::request_parameters

    class CartSetCardParams < Terminal::BaseModel
      extend Terminal::RequestParameters::Converter
      include Terminal::RequestParameters

      attr_accessor card_id: String

      def initialize:
        (card_id: String, request_options: Terminal::request_opts) -> void
        | (
          ?Terminal::Models::cart_set_card_params | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::cart_set_card_params
    end
  end
end
