module Terminal
  module Models
    type cart_set_item_params =
      { product_variant_id: String, quantity: Integer }
      & Terminal::request_parameters

    class CartSetItemParams < Terminal::BaseModel
      extend Terminal::RequestParameters::Converter
      include Terminal::RequestParameters

      attr_accessor product_variant_id: String

      attr_accessor quantity: Integer

      def initialize:
        (
          product_variant_id: String,
          quantity: Integer,
          request_options: Terminal::request_opts
        ) -> void
        | (
          ?Terminal::Models::cart_set_item_params | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::cart_set_item_params
    end
  end
end
