module Terminal
  module Models
    type email_create_response = { data: :ok }

    class EmailCreateResponse < Terminal::BaseModel
      attr_accessor data: :ok

      def initialize:
        (data: :ok) -> void
        | (
          ?Terminal::Models::email_create_response | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::email_create_response
    end
  end
end
