module Terminal
  module Models
    type email_create_params = { email: String } & Terminal::request_parameters

    class EmailCreateParams < Terminal::BaseModel
      extend Terminal::RequestParameters::Converter
      include Terminal::RequestParameters

      attr_accessor email: String

      def initialize:
        (email: String, request_options: Terminal::request_opts) -> void
        | (
          ?Terminal::Models::email_create_params | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::email_create_params
    end
  end
end
