module Terminal
  module Models
    type order_list_response = { data: Array[Terminal::Models::OrderAPI] }

    class OrderListResponse < Terminal::BaseModel
      attr_accessor data: Array[Terminal::Models::OrderAPI]

      def initialize:
        (data: Array[Terminal::Models::OrderAPI]) -> void
        | (
          ?Terminal::Models::order_list_response | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::order_list_response
    end
  end
end
