module Terminal
  module Models
    type product_variant = { id: String, name: String, price: Integer }

    class ProductVariant < Terminal::BaseModel
      attr_accessor id: String

      attr_accessor name: String

      attr_accessor price: Integer

      def initialize:
        (id: String, name: String, price: Integer) -> void
        | (
          ?Terminal::Models::product_variant | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::product_variant
    end
  end
end
