module Terminal
  module Models
    type profile_update_response = { data: Terminal::Models::ProfileAPI }

    class ProfileUpdateResponse < Terminal::BaseModel
      attr_accessor data: Terminal::Models::ProfileAPI

      def initialize:
        (data: Terminal::Models::ProfileAPI) -> void
        | (
          ?Terminal::Models::profile_update_response | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::profile_update_response
    end
  end
end
