module Terminal
  module Models
    type profile_update_params =
      { email: String?, name: String? } & Terminal::request_parameters

    class ProfileUpdateParams < Terminal::BaseModel
      extend Terminal::RequestParameters::Converter
      include Terminal::RequestParameters

      attr_accessor email: String?

      attr_accessor name: String?

      def initialize:
        (
          email: String?,
          name: String?,
          request_options: Terminal::request_opts
        ) -> void
        | (
          ?Terminal::Models::profile_update_params | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::profile_update_params
    end
  end
end
