module Terminal
  module Models
    type subscription_create_response = { data: :ok }

    class SubscriptionCreateResponse < Terminal::BaseModel
      attr_accessor data: :ok

      def initialize:
        (data: :ok) -> void
        | (
          ?Terminal::Models::subscription_create_response
          | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::subscription_create_response
    end
  end
end
