module Terminal
  module Models
    type token_create_response =
      { data: Terminal::Models::TokenCreateResponse::Data }

    class TokenCreateResponse < Terminal::BaseModel
      attr_accessor data: Terminal::Models::TokenCreateResponse::Data

      def initialize:
        (data: Terminal::Models::TokenCreateResponse::Data) -> void
        | (
          ?Terminal::Models::token_create_response | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::token_create_response

      type data = { id: String, token: String }

      class Data < Terminal::BaseModel
        attr_accessor id: String

        attr_accessor token: String

        def initialize:
          (id: String, token: String) -> void
          | (
            ?Terminal::Models::TokenCreateResponse::data
            | Terminal::BaseModel data
          ) -> void

        def to_hash: -> Terminal::Models::TokenCreateResponse::data
      end
    end
  end
end
