module Terminal
  module Models
    type token_get_response = { data: Terminal::Models::TokenAPI }

    class TokenGetResponse < Terminal::BaseModel
      attr_accessor data: Terminal::Models::TokenAPI

      def initialize:
        (data: Terminal::Models::TokenAPI) -> void
        | (
          ?Terminal::Models::token_get_response | Terminal::BaseModel data
        ) -> void

      def to_hash: -> Terminal::Models::token_get_response
    end
  end
end
