module Terminal
  module Models
    type token_api =
      { id: String, token: String, time: Terminal::Models::TokenAPI::Time }

    class TokenAPI < Terminal::BaseModel
      attr_accessor id: String

      attr_accessor token: String

      attr_accessor time: Terminal::Models::TokenAPI::Time

      def initialize:
        (
          id: String,
          token: String,
          time: Terminal::Models::TokenAPI::Time
        ) -> void
        | (?Terminal::Models::token_api | Terminal::BaseModel data) -> void

      def to_hash: -> Terminal::Models::token_api

      type time = { created: String }

      class Time < Terminal::BaseModel
        attr_accessor created: String

        def initialize:
          (created: String) -> void
          | (
            ?Terminal::Models::TokenAPI::time | Terminal::BaseModel data
          ) -> void

        def to_hash: -> Terminal::Models::TokenAPI::time
      end
    end
  end
end
