module Terminal
  class Client < Terminal::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    ENVIRONMENTS: {
      production: "https://api.terminal.shop/",
      sandbox: "https://sandbox.terminal.shop/"
    }

    attr_reader bearer_token: String

    attr_reader product: Terminal::Resources::Product

    attr_reader profile: Terminal::Resources::Profile

    attr_reader address: Terminal::Resources::Address

    attr_reader card: Terminal::Resources::Card

    attr_reader cart: Terminal::Resources::Cart

    attr_reader order: Terminal::Resources::Order

    attr_reader subscription: Terminal::Resources::Subscription

    attr_reader token: Terminal::Resources::Token

    attr_reader app: Terminal::Resources::App

    attr_reader email: Terminal::Resources::Email

    attr_reader view: Terminal::Resources::View

    private def auth_headers: -> Hash[String, String]

    def initialize: (
      environment: :production | :sandbox | nil,
      base_url: String?,
      bearer_token: String?,
      max_retries: Integer,
      timeout: Float,
      initial_retry_delay: Float,
      max_retry_delay: Float
    ) -> void
  end
end
